### ISSUE TITLE
Undefined symbols when running 'wsh'.

### ISSUE THREAD

**Issue by nihilus** [endrazine/wcc#21] opened 2017-05-01 14:05 UTC
> 
markus@markus:~/Downloads/wcc3$ /usr/bin/wsh
init
WARNING: No binary loaded in memory. Try loadbin(). For help type help("loadbin").
ERROR: /lib/x86_64-linux-gnu/libdl.so.2: undefined symbol: __pthread_key_create
ERROR: /lib/x86_64-linux-gnu/libdl.so.2: undefined symbol: _ITM_deregisterTMCloneTable
ERROR: /lib/x86_64-linux-gnu/libdl.so.2: undefined symbol: __pthread_getspecific
ERROR: /lib/x86_64-linux-gnu/libdl.so.2: undefined symbol: __gmon_start__
ERROR: /lib/x86_64-linux-gnu/libdl.so.2: undefined symbol: __pthread_once
ERROR: /lib/x86_64-linux-gnu/libdl.so.2: undefined symbol: _Jv_RegisterClasses
ERROR: /lib/x86_64-linux-gnu/libdl.so.2: undefined symbol: _ITM_registerTMCloneTable
ERROR: /lib/x86_64-linux-gnu/libdl.so.2: undefined symbol: __pthread_setspecific
ERROR: /lib/x86_64-linux-gnu/libdl.so.2: undefined symbol: GLIBC_2.2.5
ERROR: /lib/x86_64-linux-gnu/libdl.so.2: undefined symbol: GLIBC_2.3.3
ERROR: /lib/x86_64-linux-gnu/libdl.so.2: undefined symbol: GLIBC_2.3.4
ERROR: /lib/x86_64-linux-gnu/libdl.so.2: undefined symbol: GLIBC_PRIVATE
ERROR: /lib/x86_64-linux-gnu/libc.so.6: undefined symbol: _dl_starting_up
ERROR: /lib/x86_64-linux-gnu/libc.so.6: undefined symbol: _obstack
ERROR: /lib/x86_64-linux-gnu/libc.so.6: undefined symbol: get_kernel_syms
ERROR: /lib/x86_64-linux-gnu/libc.so.6: undefined symbol: _res
ERROR: /lib/x86_64-linux-gnu/libc.so.6: undefined symbol: step
ERROR: /lib/x86_64-linux-gnu/libc.so.6: undefined symbol: GLIBC_PRIVATE
ERROR: /lib/x86_64-linux-gnu/libc.so.6: undefined symbol: __ctype_tolower
ERROR: /lib/x86_64-linux-gnu/libc.so.6: undefined symbol: __ctype_b
ERROR: /lib/x86_64-linux-gnu/libc.so.6: undefined symbol: __secure_getenv
ERROR: /lib/x86_64-linux-gnu/libc.so.6: undefined symbol: GLIBC_2.3
ERROR: /lib/x86_64-linux-gnu/libc.so.6: undefined symbol: GLIBC_2.4
ERROR: /lib/x86_64-linux-gnu/libc.so.6: undefined symbol: GLIBC_2.5
ERROR: /lib/x86_64-linux-gnu/libc.so.6: undefined symbol: GLIBC_2.6
ERROR: /lib/x86_64-linux-gnu/libc.so.6: undefined symbol: __ctype_toupper
ERROR: /lib/x86_64-linux-gnu/libc.so.6: undefined symbol: GLIBC_2.7
ERROR: /lib/x86_64-linux-gnu/libc.so.6: undefined symbol: GLIBC_2.8
ERROR: /lib/x86_64-linux-gnu/libc.so.6: undefined symbol: GLIBC_2.9
ERROR: /lib/x86_64-linux-gnu/libc.so.6: undefined symbol: create_module
ERROR: /lib/x86_64-linux-gnu/libc.so.6: undefined symbol: query_module
ERROR: /lib/x86_64-linux-gnu/libc.so.6: undefined symbol: GLIBC_2.10
ERROR: /lib/x86_64-linux-gnu/libc.so.6: undefined symbol: GLIBC_2.11
ERROR: /lib/x86_64-linux-gnu/libc.so.6: undefined symbol: GLIBC_2.12
ERROR: /lib/x86_64-linux-gnu/libc.so.6: undefined symbol: GLIBC_2.13
ERROR: /lib/x86_64-linux-gnu/libc.so.6: undefined symbol: GLIBC_2.14
ERROR: /lib/x86_64-linux-gnu/libc.so.6: undefined symbol: GLIBC_2.15
ERROR: /lib/x86_64-linux-gnu/libc.so.6: undefined symbol: GLIBC_2.16
ERROR: /lib/x86_64-linux-gnu/libc.so.6: undefined symbol: GLIBC_2.17
ERROR: /lib/x86_64-linux-gnu/libc.so.6: undefined symbol: GLIBC_2.18
ERROR: /lib/x86_64-linux-gnu/libc.so.6: undefined symbol: __ctype32_tolower
ERROR: /lib/x86_64-linux-gnu/libc.so.6: undefined symbol: uselib
ERROR: /lib/x86_64-linux-gnu/libc.so.6: undefined symbol: GLIBC_2.22
ERROR: /lib/x86_64-linux-gnu/libc.so.6: undefined symbol: GLIBC_2.23
ERROR: /lib/x86_64-linux-gnu/libc.so.6: undefined symbol: advance
ERROR: /lib/x86_64-linux-gnu/libc.so.6: undefined symbol: GLIBC_2.2.5
ERROR: /lib/x86_64-linux-gnu/libc.so.6: undefined symbol: GLIBC_2.2.6
ERROR: /lib/x86_64-linux-gnu/libc.so.6: undefined symbol: __ctype32_toupper
ERROR: /lib/x86_64-linux-gnu/libc.so.6: undefined symbol: GLIBC_2.3.2
ERROR: /lib/x86_64-linux-gnu/libc.so.6: undefined symbol: GLIBC_2.3.3
ERROR: /lib/x86_64-linux-gnu/libc.so.6: undefined symbol: GLIBC_2.3.4
ERROR: /lib/x86_64-linux-gnu/libc.so.6: undefined symbol: bdflush
ERROR: /lib/x86_64-linux-gnu/libc.so.6: undefined symbol: __ctype32_b
ERROR: /lib/x86_64-linux-gnu/libc.so.6: undefined symbol: loc1
ERROR: /lib/x86_64-linux-gnu/libc.so.6: undefined symbol: loc2
ERROR: /lib/x86_64-linux-gnu/libc.so.6: undefined symbol: sigvec
ERROR: /lib/x86_64-linux-gnu/libc.so.6: undefined symbol: locs
ERROR: /lib64/ld-linux-x86-64.so.2: undefined symbol: __get_cpu_features
ERROR: /lib64/ld-linux-x86-64.so.2: undefined symbol: _dl_get_tls_static_info
ERROR: /lib64/ld-linux-x86-64.so.2: undefined symbol: GLIBC_PRIVATE
ERROR: /lib64/ld-linux-x86-64.so.2: undefined symbol: GLIBC_2.3
ERROR: /lib64/ld-linux-x86-64.so.2: undefined symbol: GLIBC_2.4
ERROR: /lib64/ld-linux-x86-64.so.2: undefined symbol: free
ERROR: /lib64/ld-linux-x86-64.so.2: undefined symbol: realloc
ERROR: /lib64/ld-linux-x86-64.so.2: undefined symbol: _dl_allocate_tls
ERROR: /lib64/ld-linux-x86-64.so.2: undefined symbol: _r_debug
ERROR: /lib64/ld-linux-x86-64.so.2: undefined symbol: __libc_stack_end
ERROR: /lib64/ld-linux-x86-64.so.2: undefined symbol: __libc_memalign
ERROR: /lib64/ld-linux-x86-64.so.2: undefined symbol: _dl_deallocate_tls
ERROR: /lib64/ld-linux-x86-64.so.2: undefined symbol: _dl_find_dso_for_object
ERROR: /lib64/ld-linux-x86-64.so.2: undefined symbol: calloc
ERROR: /lib64/ld-linux-x86-64.so.2: undefined symbol: _dl_argv
ERROR: /lib64/ld-linux-x86-64.so.2: undefined symbol: _dl_mcount
ERROR: /lib64/ld-linux-x86-64.so.2: undefined symbol: _dl_tls_setup
ERROR: /lib64/ld-linux-x86-64.so.2: undefined symbol: _dl_debug_state
ERROR: /lib64/ld-linux-x86-64.so.2: undefined symbol: _rtld_global
ERROR: /lib64/ld-linux-x86-64.so.2: undefined symbol: GLIBC_2.2.5
ERROR: /lib64/ld-linux-x86-64.so.2: undefined symbol: __tls_get_addr
ERROR: /lib64/ld-linux-x86-64.so.2: undefined symbol: _dl_make_stack_executable
ERROR: /lib64/ld-linux-x86-64.so.2: undefined symbol: malloc
ERROR: /lib64/ld-linux-x86-64.so.2: undefined symbol: _dl_allocate_tls_init
ERROR: /lib64/ld-linux-x86-64.so.2: undefined symbol: _rtld_global_ro
ERROR: /lib64/ld-linux-x86-64.so.2: undefined symbol: __libc_enable_secure
ERROR: /lib64/ld-linux-x86-64.so.2: undefined symbol: _dl_rtld_di_serinfo

>

**Comment by endrazine** [comment] 2017-05-05 22:17
Hi Nihilus,

I think this is introduced by commit 13c2b333ee5da9e09bfa890e0abb73ac3aa31bb7
We can't have all the error messages and at the same time not have all the error messages ;(
The root cause is an error message from the dynamic linker (that is totally benign and can be fairly ignored) when resolving function names which happen to be weak aliases. 

I'm adding a macro : PEDANTIC_WARNINGS , so you could compile with -D_PEDANTIC_WARNINGS=1 to have this extra dlerror() check done, else it will be silently ignored.

Thanks !

j-

**Closed** 2017-05-05 22:21 UTC

**Comment by nihilus** [comment] 2017-05-05 23:14
Nice catch, I was thinking my Ubuntu installation was fucked up
